-- Relationship metadata sample for kg_mapping auto-generation verification.
--
-- Usage:
--   Upload this file as metadata_files when calling:
--   POST /audit/kg-mapping/generate
--
-- Notes:
--   1. This file is intended as metadata input. Do not execute it against
--      the audit database unless you really want to create physical FKs.
--   2. The current parser expects simple, unquoted table and column names.
--      Avoid schema-qualified names such as public.bid_record in this file.
--   3. audit_rule, audit_result, and project_alias are excluded from KG
--      generation by default in the audit flow.

CREATE TABLE enterprise (
  enterprise_id text PRIMARY KEY,
  enterprise_name text,
  industry text,
  registered_address text,
  status text,
  business_scope varchar
);

CREATE TABLE person (
  person_id text PRIMARY KEY,
  name text,
  address text,
  is_expert integer,
  phone varchar
);

CREATE TABLE project (
  project_id text PRIMARY KEY,
  project_name text,
  tender_org_id text,
  tender_org text,
  budget numeric,
  status text,
  bid_time date
);

CREATE TABLE bid_record (
  bid_id text PRIMARY KEY,
  project_id text,
  enterprise_id text,
  bid_amount numeric,
  rank integer
);

CREATE TABLE enterprise_certificate (
  id text PRIMARY KEY,
  enterprise_id text,
  certificate_name text,
  certificate_type text,
  valid_start_date date,
  valid_end_date date,
  status text
);

CREATE TABLE enterprise_revenue (
  id text PRIMARY KEY,
  enterprise_id text,
  year integer,
  revenue_amount numeric
);

CREATE TABLE enterprise_shareholding (
  id integer PRIMARY KEY,
  enterprise_name text,
  holder_type integer,
  holder_name text,
  shareholding_ratio numeric
);

CREATE TABLE person_relation (
  id integer PRIMARY KEY,
  person_id_1 text,
  person_id_2 text,
  relation_type text
);

CREATE TABLE person_enterprise_position (
  id integer PRIMARY KEY,
  person_id text,
  enterprise_id text,
  position text,
  start_date date,
  end_date date,
  status integer,
  remark text
);

CREATE TABLE project_person_role (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id text,
  person_id text,
  enterprise_id text,
  side text,
  role_type text,
  start_date date,
  end_date date,
  status text,
  remark text
);

CREATE TABLE project_expert (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id text,
  person_id text,
  role_type text,
  status text,
  remark text
);

CREATE TABLE bid_person_role (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bid_id text,
  project_id text,
  enterprise_id text,
  person_id text,
  role_type text,
  start_date date,
  end_date date,
  status text,
  remark text
);

CREATE TABLE project_alias (
  id integer PRIMARY KEY,
  project_id text,
  alias_name varchar,
  alias_type varchar,
  remark text,
  created_at timestamp,
  updated_at timestamp
);

ALTER TABLE bid_record ADD CONSTRAINT fk_bid_record_project
  FOREIGN KEY (project_id) REFERENCES project(project_id);

ALTER TABLE bid_record ADD CONSTRAINT fk_bid_record_enterprise
  FOREIGN KEY (enterprise_id) REFERENCES enterprise(enterprise_id);

ALTER TABLE project ADD CONSTRAINT fk_project_tender_org
  FOREIGN KEY (tender_org_id) REFERENCES enterprise(enterprise_id);

ALTER TABLE enterprise_certificate ADD CONSTRAINT fk_enterprise_certificate_enterprise
  FOREIGN KEY (enterprise_id) REFERENCES enterprise(enterprise_id);

ALTER TABLE enterprise_revenue ADD CONSTRAINT fk_enterprise_revenue_enterprise
  FOREIGN KEY (enterprise_id) REFERENCES enterprise(enterprise_id);

-- Logical name-based links for shareholding records. The live table stores
-- names instead of stable IDs, so these are metadata hints for mapping
-- generation rather than physical foreign keys to execute:
-- enterprise_shareholding.enterprise_name -> enterprise.enterprise_name
-- enterprise_shareholding.holder_name -> person.name when holder_type = 1
-- enterprise_shareholding.holder_name -> enterprise.enterprise_name when holder_type = 2

ALTER TABLE person_enterprise_position ADD CONSTRAINT fk_person_enterprise_position_person
  FOREIGN KEY (person_id) REFERENCES person(person_id);

ALTER TABLE person_enterprise_position ADD CONSTRAINT fk_person_enterprise_position_enterprise
  FOREIGN KEY (enterprise_id) REFERENCES enterprise(enterprise_id);

ALTER TABLE person_relation ADD CONSTRAINT fk_person_relation_person_1
  FOREIGN KEY (person_id_1) REFERENCES person(person_id);

ALTER TABLE person_relation ADD CONSTRAINT fk_person_relation_person_2
  FOREIGN KEY (person_id_2) REFERENCES person(person_id);

ALTER TABLE project_person_role ADD CONSTRAINT fk_project_person_role_project
  FOREIGN KEY (project_id) REFERENCES project(project_id);

ALTER TABLE project_person_role ADD CONSTRAINT fk_project_person_role_person
  FOREIGN KEY (person_id) REFERENCES person(person_id);

ALTER TABLE project_person_role ADD CONSTRAINT fk_project_person_role_enterprise
  FOREIGN KEY (enterprise_id) REFERENCES enterprise(enterprise_id);

ALTER TABLE project_expert ADD CONSTRAINT fk_project_expert_project
  FOREIGN KEY (project_id) REFERENCES project(project_id);

ALTER TABLE project_expert ADD CONSTRAINT fk_project_expert_person
  FOREIGN KEY (person_id) REFERENCES person(person_id);

ALTER TABLE bid_person_role ADD CONSTRAINT fk_bid_person_role_bid
  FOREIGN KEY (bid_id) REFERENCES bid_record(bid_id);

ALTER TABLE bid_person_role ADD CONSTRAINT fk_bid_person_role_project
  FOREIGN KEY (project_id) REFERENCES project(project_id);

ALTER TABLE bid_person_role ADD CONSTRAINT fk_bid_person_role_enterprise
  FOREIGN KEY (enterprise_id) REFERENCES enterprise(enterprise_id);

ALTER TABLE bid_person_role ADD CONSTRAINT fk_bid_person_role_person
  FOREIGN KEY (person_id) REFERENCES person(person_id);

-- This relationship is useful for project matching, but project_alias is
-- excluded from graph generation by the audit defaults.
ALTER TABLE project_alias ADD CONSTRAINT fk_project_alias_project
  FOREIGN KEY (project_id) REFERENCES project(project_id);
