-- Add enterprise shareholding facts and demo data to the audit DB.
-- This script is idempotent for the current demo data set.

BEGIN;

CREATE TABLE IF NOT EXISTS enterprise_shareholding (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  enterprise_name text NOT NULL,
  holder_type integer NOT NULL,
  holder_name text NOT NULL,
  shareholding_ratio numeric NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_enterprise_shareholding_fact
  ON enterprise_shareholding (enterprise_name, holder_type, holder_name);

INSERT INTO person (person_id, name, address, is_expert, phone) VALUES
  ('P301', '王强', NULL, 0, NULL)
ON CONFLICT (person_id) DO UPDATE SET
  name = EXCLUDED.name,
  address = EXCLUDED.address,
  is_expert = EXCLUDED.is_expert,
  phone = EXCLUDED.phone;

INSERT INTO enterprise_shareholding (
  enterprise_name,
  holder_type,
  holder_name,
  shareholding_ratio
) VALUES
  ('深圳华信科技有限公司', 1, '张伟', 42.50),
  ('深圳华信科技有限公司', 2, '深圳智达信息有限公司', 18.00),
  ('深圳智达信息有限公司', 1, '李娜', 35.00),
  ('深圳云创数据有限公司', 2, '深圳华信科技有限公司', 22.00),
  ('广东安科信息技术有限公司', 2, '深圳云创数据有限公司', 12.00),
  ('广州启明数字工程有限公司', 1, '王强', 28.00),
  ('广新控股集团', 1, '王强', 12.00)
ON CONFLICT (enterprise_name, holder_type, holder_name) DO UPDATE SET
  shareholding_ratio = EXCLUDED.shareholding_ratio;

INSERT INTO bid_person_role (
  bid_id,
  project_id,
  enterprise_id,
  person_id,
  role_type,
  start_date,
  end_date,
  status,
  remark
) VALUES
  ('B101', 'PJT101', 'E001', 'P001', 'SHAREHOLDER_REPRESENTATIVE', '2025-01-01', NULL, 'active', '股东本人参与投标样例')
ON CONFLICT (bid_id, person_id, role_type) DO UPDATE SET
  project_id = EXCLUDED.project_id,
  enterprise_id = EXCLUDED.enterprise_id,
  start_date = EXCLUDED.start_date,
  end_date = EXCLUDED.end_date,
  status = EXCLUDED.status,
  remark = EXCLUDED.remark;

COMMIT;
