-- Add compiled graph-path rule configs for deterministic multi-hop queries.
-- Business users maintain audit_rule; this hidden table stores validated
-- machine-executable graph traversal constraints.

BEGIN;

CREATE TABLE IF NOT EXISTS audit_rule_graph_config (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rule_id integer NOT NULL REFERENCES audit_rule(id) ON DELETE CASCADE,
  config jsonb NOT NULL,
  basis_hash text,
  status text NOT NULL DEFAULT 'active',
  created_at timestamp NOT NULL DEFAULT now(),
  updated_at timestamp NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_audit_rule_graph_config_rule_status
  ON audit_rule_graph_config (rule_id, status);

INSERT INTO audit_rule (
  rule_name,
  rule_basis,
  rule_status,
  rule_type,
  remark
)
SELECT
  '招投标人际关系穿透风险',
  '投标企业、招标单位、相关人员之间存在亲属、同事、任职、持股、共同项目投标等多跳关联关系时，应作为招投标风险线索进行穿透核查。',
  '1',
  '招投标人际关系风险',
  '系统默认多跳图谱查询规则'
WHERE NOT EXISTS (
  SELECT 1
  FROM audit_rule
  WHERE rule_type = '招投标人际关系风险'
    AND rule_status IN ('1', 'enabled', 'active', '启用')
);

WITH target_rule AS (
  SELECT id
  FROM audit_rule
  WHERE rule_type = '招投标人际关系风险'
    AND rule_status IN ('1', 'enabled', 'active', '启用')
  ORDER BY id
  LIMIT 1
)
INSERT INTO audit_rule_graph_config (
  rule_id,
  config,
  basis_hash,
  status
)
SELECT
  id,
  '{
    "allowed_entity_types": [
      "Person",
      "Organization",
      "Project",
      "BidSubmission",
      "ShareholdingRecord"
    ],
    "relation_types": [
      "PERSON_RELATED",
      "HOLDS_POSITION",
      "PROJECT_PERSON_ROLE",
      "PROJECT_ROLE_ORG",
      "BID_PERSON_ROLE",
      "BID_ROLE_ORG",
      "BIDDER",
      "FOR_PROJECT",
      "TENDERED_BY",
      "SHAREHOLDING_TARGET",
      "NATURAL_PERSON_SHAREHOLDER",
      "ENTERPRISE_SHAREHOLDER"
    ],
    "default_max_depth": 4
  }'::jsonb,
  'manual-audit-graph-config-v1',
  'active'
FROM target_rule
WHERE NOT EXISTS (
  SELECT 1
  FROM audit_rule_graph_config existing
  WHERE existing.rule_id = target_rule.id
    AND existing.basis_hash = 'manual-audit-graph-config-v1'
);

COMMIT;
