-- Add project expert committee facts and demo data to the audit DB.
-- This script is idempotent for the current demo data set.

BEGIN;

CREATE TABLE IF NOT EXISTS project_expert (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id text NOT NULL,
  person_id text NOT NULL,
  role_type text NOT NULL,
  status text,
  remark text
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_project_expert_fact
  ON project_expert (project_id, person_id, role_type);

INSERT INTO person (person_id, name, address, is_expert, phone) VALUES
  ('P009', '陈工', '深圳市南山区科技园A座10楼', 1, NULL),
  ('P010', '黄婷', '宝安区西乡街道', 1, NULL),
  ('P120', '吴评委', '深圳市福田区深南大道88号', 1, NULL),
  ('P121', '周评委', '广州市天河区软件路18号', 1, NULL),
  ('P122', '郑评委', '深圳市南山区科技园B座7楼', 1, NULL)
ON CONFLICT (person_id) DO UPDATE SET
  name = EXCLUDED.name,
  address = EXCLUDED.address,
  is_expert = EXCLUDED.is_expert,
  phone = EXCLUDED.phone;

INSERT INTO project_expert (
  project_id,
  person_id,
  role_type,
  status,
  remark
) VALUES
  ('PJT101', 'P009', 'EVALUATION_EXPERT', 'active', '地址相似样例：与深圳华信科技有限公司人员张伟/张敏同在南山区科技园A座'),
  ('PJT101', 'P120', 'EVALUATION_EXPERT', 'active', '广新智慧采购监管平台评委'),
  ('PJT102', 'P122', 'EVALUATION_EXPERT', 'active', '地址相似样例：与深圳智达信息有限公司人员李强/李娜同在南山区科技园B座'),
  ('PJT102', 'P010', 'EVALUATION_EXPERT', 'active', '南山政务数据治理平台评委'),
  ('PJT103', 'P121', 'EVALUATION_EXPERT', 'active', '地址相同样例：与广东安科信息技术有限公司人员地址一致')
ON CONFLICT (project_id, person_id, role_type) DO UPDATE SET
  status = EXCLUDED.status,
  remark = EXCLUDED.remark;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_project_expert_project') THEN
    ALTER TABLE project_expert
      ADD CONSTRAINT fk_project_expert_project
      FOREIGN KEY (project_id) REFERENCES project(project_id);
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_project_expert_person') THEN
    ALTER TABLE project_expert
      ADD CONSTRAINT fk_project_expert_person
      FOREIGN KEY (person_id) REFERENCES person(person_id);
  END IF;
END $$;

COMMIT;
