-- Seed active hidden graph traversal configs for the four audit rule types.
-- Idempotent at the active-config level: current active configs are inactivated
-- and a fresh active config is inserted for each matching rule.

BEGIN;

CREATE TABLE IF NOT EXISTS audit_rule_graph_config (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rule_id integer NOT NULL REFERENCES audit_rule(id) ON DELETE CASCADE,
  config jsonb NOT NULL,
  basis_hash text,
  status text NOT NULL DEFAULT 'active',
  created_at timestamp NOT NULL DEFAULT now(),
  updated_at timestamp NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_audit_rule_graph_config_rule_status
  ON audit_rule_graph_config (rule_id, status);

WITH templates(rule_type, config, basis_hash) AS (
  VALUES
    (
      '人际关系',
      '{
        "allowed_entity_types": ["Person", "Organization", "Project", "BidSubmission", "ShareholdingRecord"],
        "relation_types": [
          "PERSON_RELATED",
          "HOLDS_POSITION",
          "PROJECT_PERSON_ROLE",
          "PROJECT_ROLE_ORG",
          "PROJECT_EXPERT",
          "BID_PERSON_ROLE",
          "BID_ROLE_ORG",
          "BIDDER",
          "FOR_PROJECT",
          "TENDERED_BY",
          "BID_PERSON_ROLE",
          "BID_ROLE_ORG",
          "SHAREHOLDING_TARGET",
          "NATURAL_PERSON_SHAREHOLDER",
          "ENTERPRISE_SHAREHOLDER"
        ],
        "default_max_depth": 4
      }'::jsonb,
      'builtin-人际关系-v1'
    ),
    (
      '股权关系',
      '{
        "allowed_entity_types": ["Person", "Organization", "Project", "BidSubmission", "ShareholdingRecord"],
        "relation_types": [
          "BIDDER",
          "FOR_PROJECT",
          "TENDERED_BY",
          "BID_PERSON_ROLE",
          "BID_ROLE_ORG",
          "SHAREHOLDING_TARGET",
          "NATURAL_PERSON_SHAREHOLDER",
          "ENTERPRISE_SHAREHOLDER"
        ],
        "default_max_depth": 4
      }'::jsonb,
      'builtin-股权关系-v2'
    ),
    (
      '地址关联',
      '{
        "allowed_entity_types": ["Person", "Organization", "Project", "BidSubmission", "ShareholdingRecord"],
        "relation_types": [
          "PERSON_RELATED",
          "HOLDS_POSITION",
          "PROJECT_PERSON_ROLE",
          "PROJECT_ROLE_ORG",
          "PROJECT_EXPERT",
          "BID_PERSON_ROLE",
          "BID_ROLE_ORG",
          "BIDDER",
          "FOR_PROJECT",
          "TENDERED_BY",
          "SHAREHOLDING_TARGET",
          "NATURAL_PERSON_SHAREHOLDER",
          "ENTERPRISE_SHAREHOLDER"
        ],
        "default_max_depth": 4
      }'::jsonb,
      'builtin-地址关联-v1'
    ),
    (
      '投标行为',
      '{
        "allowed_entity_types": ["Person", "Organization", "Project", "BidSubmission"],
        "relation_types": [
          "BIDDER",
          "FOR_PROJECT",
          "TENDERED_BY",
          "BID_PERSON_ROLE",
          "BID_ROLE_ORG",
          "PROJECT_PERSON_ROLE",
          "PROJECT_ROLE_ORG"
        ],
        "default_max_depth": 4
      }'::jsonb,
      'builtin-投标行为-v1'
    )
),
target_rules AS (
  SELECT
    ar.id AS rule_id,
    ar.rule_type,
    t.config,
    t.basis_hash
  FROM audit_rule ar
  JOIN templates t ON t.rule_type = ar.rule_type
  WHERE ar.rule_status IN ('1', 'enabled', 'active', '启用')
),
inactive AS (
  UPDATE audit_rule_graph_config argc
  SET status = 'inactive', updated_at = now()
  FROM target_rules tr
  WHERE argc.rule_id = tr.rule_id
    AND argc.status = 'active'
  RETURNING argc.id
)
INSERT INTO audit_rule_graph_config (
  rule_id,
  config,
  basis_hash,
  status
)
SELECT
  tr.rule_id,
  tr.config,
  tr.basis_hash,
  'active'
FROM target_rules tr;

COMMIT;
